image: python:3.9

stages:
  - test

before_script:
  - python -V  # Print out python version for debugging
  - pip install -r requirements.txt

flake8:
  stage: test
  script:
    - pip install flake8
    - flake8

pytest:
  stage: test
  script:
    - pip install pytest
    - pytest