name: Tests and Merge

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12.4"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        pytest -p no:warnings src/test_fastapi.py

    - name: Run mypy
      run: |
        mypy src/

    - name: Run black
      run: |
        black --diff --check src/

    - name: Run isort
      run: |
        isort --check-only --profile black src/

    - name: Run flake8
      run: |
        flake8 src/