name: Tests and Merge

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12.4"]

    steps:
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest -p no:warnings src/test_fastapi.py

      - name: Run mypy
        run: |
          mypy src/

      - name: Run black
        run: |
          black --diff --check src/

      - name: Run isort
        run: |
          isort --check-only --profile black src/

      - name: Run flake8
        run: |
          flake8 src/

      - name: Merge to main
        if: github.event_name == 'pull_request' && success()
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'
          git merge origin/tests
          git push origin main